project_id = "eyyovobwgaqeizfxmkox"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.heartbeat]
verify_jwt = false

[functions.admin-seed-delib]
verify_jwt = true

[functions.signals-push]
verify_jwt = false

[functions.capacity-brain-activate]
verify_jwt = true

[functions.capacity-brain-override]
verify_jwt = true

[functions.capacity-brain-create-task]
verify_jwt = true