// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyyovobwgaqeizfxmkox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5eW92b2J3Z2FxZWl6Znhta294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTExODUsImV4cCI6MjA3MTA2NzE4NX0.ieo7c11vEhdWxWKTf4C61PgOdFO7_NT2v9eCAqZMECs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});